adding core program and container procedure

diff --git a/server-vcl/Containerfile b/server-vcl/Containerfile
--- a/server-vcl/Containerfile
+++ b/server-vcl/Containerfile
@@ -21,7 +21,7 @@ RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
 
 RUN pip3.11 install --no-cache-dir uvicorn fastapi gunicorn
 
-RUN useradd appCore
+RUN useradd -u 1000 -m appCore
 RUN mkdir app/
 RUN chown appCore:appCore app/
 
@@ -31,9 +31,10 @@ USER appCore
 
 CMD ["/bin/bash", "-c", "\
     if [ -f \"pyproject.toml\" ]; then \
-        pip install --user --no-cache-dir -e \"/app\"; \
+        pip install --user --no-cache-dir \".[datasci, dev, dist, web]\" || echo 'Pip install failed, skipping...'; \
     fi && \
-    python3 -m gunicorn \"src.${core_project}.main:app\" \
+    export PYTHONPATH=\"/app/src:${PYTHONPATH}\" && \
+    python3 -m gunicorn \"${core_project}.main:app\" \
     --workers 2 \
     --worker-class uvicorn.workers.UvicornWorker \
     --bind 0.0.0.0:8080 \
